<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Rinaldo" failures="1" tests="4" name="Test2000" time="0.272" errors="0" timestamp="2023-12-18T17:26:54 IST">
  <testcase classname="com.mystore.testcases.RetryTestCase" name="Demo1" time="0.01"/>
  <testcase classname="com.mystore.testcases.RetryTestCase" name="Demo2" time="0.001"/>
  <testcase classname="com.mystore.testcases.RetryTestCase" name="Demo3" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [15] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [15] but found [1]
at com.mystore.testcases.RetryTestCase.Demo3(RetryTestCase.java:23)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Demo3 -->
  <testcase classname="com.mystore.testcases.RetryTestCase" name="Demo4" time="0.001"/>
</testsuite> <!-- Test2000 -->
